### ISSUE TITLE
No sound on weld connection and after weld. (More of a suggestion)

### ISSUE THREAD

**Issue by 420pootang69** [KaeptnBalu/Arduino_Spot_Welder_V4#4]
I've used some of the cheaper welders over the years and they always give an audible indication of the weld taking place. Seemed weird it wasn't on here. I also wanted one when the probes where detected.

Maybe it's just me, but I really prefer the additional audio feedback.

I did a quick hack on mine, just including the code to show you what I mean.

	if ( shortPulseDelay < 1 ) shortPulseDelay = 1;

	tone(PIN_BUZZ, 1000, 200);

	// Wait the pulse engagement delay time.
	if ( sensePin == PIN_AUTO_PULSE ) {
		wait.opt = PGR_ON;
		wait.time = delayEngage;

		while ( !drawProgress( &wait, false ) ) {
			if ( digitalRead( PIN_AUTO_PULSE ) != activePinState ) {
				drawProgress( &wait, true );
				return;
			}
		}
	} else {
		delay( delayEngage );
	}
 	
	tone(PIN_BUZZ, 1000, 200);

	if ( pData.shortPulseTime > 0 && pData.pulseTime > 3 ) {
		// Send the pre-heat pulse.
		weldPulse( P_ON );
		delay( shortPulseDelay );
		weldPulse( P_OFF );

		// Wait the inter-pulse delay time.
		delay( shortPulseDelay );
	}
	
As I said, just a suggestion for a software update going forward.

**Comment by KaeptnBalu** [comment]
Thank you for that idea. I will implement it in the next software version. I think it is best to make the sound selectable in the menu. So the user can decide if they want to turn it on or off.
